hummingbird-me/kitsu-mobile

src/common/styles.js
src/screens/Profiles/UserLibrary/components/UserLibraryScreen/constants.js
src/screens/Profiles/UserLibrary/components/UserLibraryScreen/styles.js

Adding a `flattenCommon` export to `kitsu/common/styles` which makes it easier to include common styles into self-defined styles.

fixing styles for empty states on user library

---

src/components/SimpleHeader/component.js
src/components/SimpleHeader/index.js
src/components/SimpleHeader/styles.js

Simple header component
I might eventually refactor the ProfileHeader to just use this component. If building a screen with a header that has a left/middle/right content, use this component
```
<SimpleHeader
leftContent="Cancel"
leftAction={this.props.navigation.goBack}
titleContent="Edit Entry"
rightContent="Save"
rightAction={this.saveLibraryEntry}
/>
```
Each content can also just be a renderable...

adding simple header component

---

src/components/SearchBox/styles.js
src/screens/Sidebar/Blocking.js

- Fixes the crash caused by `SearchBox` component. Apparently, it's no longer connected to Algolia.
- Corrects search box height. @BilalBudhani [let's keep this 40 since it slices the text on Android & iOS](https://github.com/hummingbird-me/kitsu-mobile/commit/1a573a7fff32082e536344abe2f1f10c29460e18#diff-38e6f494a67ce82766e623e21253efcdR11)

Fixes Blocking Screen Crash

---

src/components/ContentList/styles.js
src/components/MediaCard/styles.js
src/components/SearchBox/styles.js

Trello Card Link: https://trello.com/c/stPAKJmW/109-sizing-and-spacing-does-not-match-design

Fixes fonts & spacing issues in search screen

---

package.json
src/screens/Feed/index.js
yarn.lock

It was available because I was debugging so it came from Chrome Debugger Tools, but when I ran without debugging the app crashed. Also removed the `url` module because it doesn't seem to be used anywhere in the app.

Fixing import issue with URL.

---

src/routes/sidebar.js
src/screens/Search/SearchScreen/index.js
src/screens/Search/SearchScreen/styles.js
src/screens/Sidebar/SidebarScreen.js

- Sidebar screen tapping on name goes to new user profile screen
- Match search tabs to home tabs
Before:
After:

Minor fixes & improvements

---

src/components/ContentList/ContentListHeader.js
src/components/ContentList/ItemRenderer.js
src/components/ContentList/component.js
src/components/ContentList/styles.js
src/components/MediaCard/component.js
src/components/MediaCard/styles.js
src/routes/search.js
src/screens/Search/Lists/TopsList/index.js
src/screens/Search/SeasonScreen.js
src/screens/Search/index.js

**Changes:**
- Seasons will update dynamically on the anime explore/search page.
- It will show the next season, current season and the previous 2 years worth of seasons.
- Fixed ContentList styling.
- Made it look more like the horizontal list in the media pages (scrolling goes all the way to the edge of the screen).
- Added placeholder items when anime/manga top lists are being loaded.
- Added a visibility prop for `View All` since not all list items needed it.
- Added a SeasonScreen which can be accessed when users tap `View All` in `Anime By Seasons`.
- Removed unnecessary lists from Manga (Seasons, Streaming)
-----
**To Do / Issues to be fixed:**
- Hook up Season, Streaming and Category taps to search results.
- When top anime/manga is loading, UI is blocked (i.e can’t view manga or …

Search page improvements

---

src/config/api.js
src/screens/Feed/components/Comment/component.js
src/screens/Feed/components/Comment/styles.js
src/screens/Feed/components/CommentTextInput/component.js
src/screens/Feed/components/Post/component.js
src/screens/Feed/index.js
src/screens/Feed/pages/PostDetails.js
src/utils/preprocessFeed.js

This PR grew a little larger than I would have liked, sorry about that... first time with RN. Let me know any changes/cleanup needed!
- Changed logic so we don't re-request comments when a posts has zero likes.
- Increased comment display from 1 -> 2 on home feed page
- Handle weird case when an activity returned from stream API didn't have a target (de-sync between DB/Stream maybe?)
- Avatar's on comments seem to re-render upon any state change

Comment pagination, replies, and likes

---

src/screens/Feed/components/EmbeddedContent/component.js

- Force embed images and video widths and heights to be of type Int.
- Handle case where embed.kind is empty.
- Update prop types to accept both string and int for width and height because embeds can't make their minds up.

[Fix] Embed bugs leading to crashes

---

src/common/utils/url.js

- Added custom URL parser
- We were using `URL` object before but that doesn't exist in iOS and Android.

[Fix] URLs not being clickable on both devices.

---

src/routes/onboarding.js
src/screens/Auth/AuthScreen.js
src/screens/Intro/RegistrationScreen.js
src/screens/Onboarding/Aozora/CreateAccountScreen.js
src/screens/Onboarding/Aozora/styles.js
src/screens/Onboarding/common/ManageLibrary.js
src/screens/Sidebar/Library/ImportLibrary.js
src/store/auth/actions.js
src/store/auth/reducer.js
src/store/user/actions.js
src/store/user/reducer.js

- Automatically skip anime library rating in on boarding if `kitsu` account has more than 5 library entries.
- Added error handling in `CreateAccountScreen`.
- Added pre-population of email field in `CreateAccountScreen` if user logged in with Facebook.
- Fixed up facebook login/signup flow.
- Fixed library import showing 'AniList' for 'Aozora' imports.

[Fix]More on-boarding issues

---

src/screens/Feed/components/Comment/component.js
src/screens/Feed/components/Post/component.js
src/screens/Feed/index.js
src/screens/Feed/pages/PostDetails.js

- Fixes issue with mentioning users by pulling down slugs and mentioning by slug or falling back to id.
- Fixes issue with comments being placed on incorrect posts after a refresh. This was due to using `index` as the key in the `FlatList`.
- Hack fix to sync comments between the `Feed` & `PostDetails` page. Prior to this change if you made a comment on the `PostDetails` page and navigated back, it would disappear until a complete feed refresh or app restart.
- Fixes issue with feed refresh not pulling down latest like and comment data for updated posts.

Feed Updates

---

.travis.yml
android/fastlane/Fastfile
ios/fastlane/Fastfile

This is because both TestFlight and Google Play allow us to push an alpha build into beta manually and thus we don't need the beta automated processes.
Whenever we want to release beta, just promote the alpha build.

[Fix] Removed beta lanes.

---

src/screens/Profiles/UserLibrary/components/UserLibraryEditScreen/component.js
src/screens/Profiles/UserLibrary/components/UserLibraryListCard/component.js

:arrow_up:
- Also fixes a bug with going back to the card screen after an edit. Can't call `includes` on an object.

Fix editing status from library edit modal

---

src/routes/quickUpdate.js
src/screens/Feed/index.js
src/screens/QuickUpdateScreen/QuickUpdate.js
src/screens/QuickUpdateScreen/QuickUpdateCard/component.js

- Don't render comments as posts in the feed.
- Don't re-fetch the library entry after updating, instead just
use the response given. This saves a network request per update.
- Implement navigation to Posts and update route stack to include
user ProfilePage and post PostDetails.
- Code cleanup (Variable renames)
- Pagination (4 per page)
- Fix race condition on feeds and fast swiping

Updates to Quick Update

---

src/screens/Sidebar/CannyBoard/component.js

Switched from padding to margin so web view scales properly on android

[Fix] Canny keyboard overlap.

---

src/common/utils/url.js
src/constants/app.js
src/screens/Profiles/ProfilePages/index.js
src/screens/Profiles/components/EditModal/component.js
src/screens/Profiles/components/EditModal/styles.js
src/screens/Profiles/constants.js
src/utils/coverImage.js

**Changes:**
- Fixed `getImgixCover` ignoring cache bust integer.
- If a url now has no cache bust, then it will apply it automatically.
- Added image cache bust after user edits profile.
- Before when a user edited the profile and it reloaded, the old cover image was shown. This now applies a cache bust which will show the new cover.
- Made `EditModal` use imgix covers.
- Fixed possible crash fixes when parsing url or getting imgix cover.
- Moved cover image dimensions to a constant.
- Doubled cover image dimension when changing cover so that you don't get blurry covers on the website.

[Fix]Image cache bust

---

android/fastlane/Fastfile

- Made it upload the build to the `alpha` track and from there we can manually promote it to production.
- This needs to be looked into further in the future, but for now since we're kind of bogged down with bugs/crashes this should be fine.

[Fix] Fastlane android release

---

src/screens/Feed/components/CommentTextInput/component.js
src/screens/Feed/components/CommentTextInput/styles.js
src/screens/Feed/pages/PostCreation/CreatePost.js
src/screens/Profiles/UserLibrary/components/UserLibraryEditScreen/component.js

Since updating RN versions, they have fixed the issue with android multiline. This PR removed the hack we were using before.

[Fix] Removed multiline hack for android.

---

src/App.js
src/screens/Auth/SplashScreen.js

Added loading indicator to PersistGate.
Fixed login screen taking user back to intro after the following have occured:
1. persist timed out.
2. user clicked login.
Added rehydrate prop check on splash.

[Fix] minor fixes.

---

src/components/SearchBox/component.js
src/components/SearchBox/styles.js
src/screens/Feed/components/GiphyModal/component.js
src/screens/Feed/components/MediaModal/component.js
src/screens/Library/LibrarySearch/component.js
src/screens/Search/SearchScreen/index.js
src/screens/Sidebar/Blocking.js

This PR fixes issues that users had when they typed into the search box and the screen went blank.
The issue was with setting `textAlign: center` on a `TextInput` when it was a child of a `ScrollView`. Still don't have any idea why this is the case and it only seemed to occur on older android devices (< 5.0) but there was no conclusive way to ascertain this.
Due to this, i went with redesigning the **Search Box** such that it wouldn't use the above property in its styling.
This change affects all places where the `SearchBox` was used, which include:
- Search page
- Find a gif
- Tag media
- User library search
- User blocking
Tested and working on both Android and iOS.

[Fix] Search Issues

---

README.md

The Github page shows up in searches of "Android Kitsu" etc., so it is important that there will be a way to download it for regular users.
Additionally, having the links here may improve the store pages SEO ranking, so that those show up first.

Added download links to the live app

---

src/screens/Feed/components/PostCreator/component.js

Button is only shown if we have more than 1 url or if the current embed is different from the first url.

[Fix] 'Change Embed' button

---

android/app/build.gradle
ios/kitsu_mobile/Info.plist
package.json
src/config/env.js
src/navigation/index.js

The fix before didn't work so i just disabled setting `badgeColor` if it's a iOS 9 device.

[Fix] iOS 9 crash
