hummingbird-me/kitsu-mobile

- src/Router.js
- src/routes/filter.js
- src/routes/index.js
- src/routes/navigationOptions.js
- src/routes/notification.js
- src/routes/profile.js
- src/routes/search.js
- src/routes/tabs.js
When I first looked at the `Router.js` file, It felt overwhelmingly large to consume & convert into a mental model. So, I thought this could a good starting point for me to contribute. Let me know what you guys think.
> Refactors routes into their specific files

- src/components/Rating/component.js
- src/components/Rating/styles.js
A couple really minor things on the rating component that don't render well in Android fixed.
> Rating component android fixes

- README.md
Just updated README to look a bit nicer and to have more specific installation instructions.
Let me know if i need to add anything else.
> Updated instructions and formatting in README.

- src/components/MediaCard/component.js
- src/components/ProgressiveImage/component.js
- src/screens/Profiles/ProfileScreen.js
- src/screens/Profiles/UserLibrary/components/UserLibraryListCard/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryListScreen/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryScreen/component.js
- src/store/profile/actions.js
A misunderstanding from Josh led me to block users from being able
to increment/decrement progress quickly. Addded some calculated limits
to the fetch request for libraries in an attempt to improve load time.
> User Library Screen Improvements

- android/app/src/main/AndroidManifest.xml
- src/components/MediaUploader/MediaSelectionGrid.js
This makes the MediaUpload screen work on Android.
> Camera roll android fixes

- ios/kitsu_mobile.xcodeproj/project.pbxproj
- src/screens/Profiles/ProfileScreen.js
Previously added InteractionManager to test UI improvements, which obviously made the ProfileScreen crash. This PR fixes that.
> Profile screen correction

- src/components/Counter/component.js
- src/components/Counter/styles.js
- src/components/MediaCard/component.js
- src/components/ProgressBar/component.js
- src/components/SearchBox/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryListCard/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryListCard/styles.js
- src/screens/Profiles/UserLibrary/components/UserLibraryListScreen/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryScreen/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryScreen/styles.js
- yarn.lock
Just some polish work for the User Library pages.
> User library polish

- src/components/Forms/LoginForm.js
- src/screens/Auth/LoginScreen.js
Currently login functionality is not working because a parameter is not passed to `onSubmit` function.
> Fixes login's onSumbmit issue

- package.json
- src/components/Card/CardTabs.js
- src/screens/Profiles/FavoriteMedia.js
- src/screens/Profiles/NetworkScreen.js
- yarn.lock
Hey @edencakir 
I did what you did but found a few errors -- this has the fixes needed for those errors and we should be able to push this one! Both IOS and Android are building again.
> downgrading to .46 and fixing errors

- src/screens/Search/Lists/UsersList.js
- src/screens/Search/SearchScreen/index.js
Reverts hummingbird-me/kitsu-mobile#69
> Revert "WIP: User search improvements"

- src/components/Forms/LoginForm.js
- src/components/Forms/RecoveryForm.js
- src/components/Forms/SignupForm.js
- src/components/Forms/styles.js
- src/components/Input/component.js
- src/screens/Auth/RecoveryScreen.js
- src/screens/Auth/styles.js
Completed forgot password screen draft
> New Auth Screen

- src/components/Button/component.js
- src/components/Forms/SignupForm.js
- src/components/Forms/styles.js
- src/components/Toast/component.js
- src/components/Toast/index.js
- src/components/Toast/styles.js
- src/constants/app.js
- src/screens/Auth/AuthScreen.js
- src/screens/Auth/styles.js
- src/store/auth/actions.js
- Implements error modal ( dismissable but doesn't stay on top of the keyboard)
- Fixes login issues
- Adds linking to terms & service: https://kitsu.io/terms
- Checks whether password match and if there is an empty field
Tested on iOS and Android.
> Error states & login functionality

- src/config/api.js
- src/screens/Feed/components/Post/component.js
- src/screens/Feed/feedStreams.js
- src/screens/Feed/index.js
- src/screens/Feed/pages/PostDetails.js
Multi-feed support and a few other bug fixes.
> Multi-feed support

- src/components/Counter/component.js
- src/components/Rating/component.js
- src/store/profile/actions.js
Just a few simple fixes for the user library page.
https://trello.com/c/lW9J5xlL
> Small User Library Fixes

- src/screens/Feed/components/Post/PostOverlays/NotSafeForWork/component.js
- src/screens/Feed/components/Post/PostOverlays/NotSafeForWork/index.js
- src/screens/Feed/components/Post/PostOverlays/OverlayBase/component.js
- src/screens/Feed/components/Post/PostOverlays/OverlayBase/index.js
- src/screens/Feed/components/Post/PostOverlays/OverlayBase/styles.js
- src/screens/Feed/components/Post/PostOverlays/Spoiler/component.js
- src/screens/Feed/components/Post/PostOverlays/Spoiler/index.js
- src/screens/Feed/components/Post/component.js
This is NSFW and Spoiler support for the feed.
> Added support for post overlays.

- src/screens/Onboarding/Aozora/WelcomeScreen.js
- src/store/auth/actions.js
- src/store/onboarding/reducer.js
- src/store/user/actions.js
Hopefully this will fix the welcome screen crash.
> signup onboarding routing & crash fix

- src/store/app/reducer.js
Debugged notification screen on phone for push notification purpose & fixed show/hide of notice box
> Notification screen fix

- src/config/api.js
- src/screens/Feed/index.js
- src/screens/Profiles/MediaPages/pages/Summary.js
- src/utils/preprocessFeed.js
This involved:
- Moving preprocessing of feeds into a utility function.
- Fixing the API definition for media feeds.
- Adding logic for including the feeds in media pages themselves.
> Added feeds to the media page

- src/components/SearchBox/styles.js
- src/routes/notification.js
- src/routes/onboarding.js
- src/routes/quickUpdate.js
- src/routes/search.js
- src/routes/tabs.js
- src/screens/Feed/components/TabBar/styles.js
- src/screens/Feed/index.js
- src/screens/Notifications/NotificationsScreen.js
- src/screens/QuickUpdateScreen/styles.js
- src/screens/Search/SearchScreen/styles.js
- src/screens/Sidebar/common/SidebarHeader.js
- src/screens/Sidebar/styles.js
- Search screen api hook & crash fixed
- Android tabbars restored
- Added margins to Feed, Search, QuickUpdate and Notification screens (android).
- SearchBox height increased from 29 to 40 (_react docs recommendation_) - it might effect iOS search screen box height design, but definitely fixed android character slicing
- Sidebar Screen navigation bars android height improved (there is room for further improvement)
> Some fixes

- src/config/env.js
- src/routes/tabs.js
- src/screens/Notifications/NotificationsScreen.js
- src/screens/Sidebar/SidebarScreen.js
- src/screens/Sidebar/styles.js
- src/store/auth/actions.js
- Fixes notification screen crash
- Fixes logout button crash 🎉 
- Disables dev mode for now
- Disables android tab screen swipe
> Fix Notifications & Log out button crash

- src/components/ContentList/ItemRenderer.js
- src/routes/notification.js
- src/screens/Feed/pages/PostDetails.js
- src/screens/Notifications/NotificationsScreen.js
- src/screens/Profiles/MediaPages/index.js
- src/screens/Search/SearchResults.js
- src/screens/Search/SearchScreen/index.js
- Like, comment and post notifications navigate to the corresponding post
- Follow notifications navigate to follower's profile
- Since reactions don't have pages yet, it temporarily goes to their respective media page.
> Notification Screen hooks

- src/routes/search.js
- src/routes/tabs.js
- src/screens/Notifications/NotificationsScreen.js
- src/screens/Profiles/MediaPages/index.js
- src/screens/Profiles/components/ReactionBox/component.js
- src/screens/Search/SearchScreen/index.js
- Search anime on press now shows media page
- Notifications on press reaction like shows media page
> Fixes media screen related bugs

- android/build.gradle
See https://stackoverflow.com/questions/47671206/getting-error-when-run-react-native-run-android
> Temp fix broken run-android

- README.md
> Add links to the other repos in README

- README.md
> docs: fix link to api docs repository

- README.md
> Updates Readme with common packager error

- src/components/NavigationHeader.js
- src/components/NavigationHeader/component.js
- src/components/NavigationHeader/index.js
- src/components/NavigationHeader/styles.js
- src/components/SimpleHeader/styles.js
- src/screens/Profiles/FavoriteCharacters.js
- src/screens/Profiles/NetworkScreen.js
- src/screens/Search/FilterSub.js
- src/screens/Search/SearchCategory.js
- src/screens/Search/SearchFilter.js
- src/screens/Search/SearchResults.js
- src/screens/Search/SeasonScreen.js
**Changes:**
- Added `NavigationHeader` component which uses `SimpleHeader`.
- Updated `SimpleHeader` styling so that the navigation bar is a bit taller.
- Replaced old navigation with the new one.
- Mostly changes navigation of Search screen, nothing else.
- Tested on Android and it all works properly
> Fixes up navigation for search.

- src/screens/Feed/index.js
> Add activity indicator to feed pagination

- src/screens/Feed/pages/PostDetails.js
- src/screens/Notifications/NotificationsScreen.js
Fixes comments not loading properly when navigating from a notification.
> Fix notification navigation to posts

- src/screens/Feed/components/Comment/component.js
- src/screens/Feed/components/Post/component.js
- src/screens/Feed/pages/PostDetails.js
Provide instant UI feedback when liking posts/comments
> Feedback on liking

- src/screens/Feed/components/Comment/component.js
- src/screens/Feed/components/Post/component.js
- src/screens/Feed/components/Post/styles.js
- src/screens/Feed/pages/PostDetails.js
Implement comment reply banner similar to FB, IG, etc.
> Comment reply banner

- src/components/Forms/RecoveryForm.js
- src/components/Toast/component.js
- src/screens/Auth/RecoveryScreen.js
Implement password reset functionality :+1:
> Password Reset

- ios/kitsu_mobile.xcodeproj/project.pbxproj
- package.json
- src/components/StyledText/component.js
- src/routes/search.js
- src/screens/Feed/components/Comment/component.js
- src/screens/Feed/components/Comment/styles.js
- src/screens/Feed/components/CommentTextInput/component.js
- src/screens/Feed/components/CommentTextInput/styles.js
- src/screens/Feed/components/CreatePostRow/component.js
- src/screens/Feed/components/EmbeddedContent/component.js
- src/screens/Feed/components/EmbeddedContent/index.js
- src/screens/Feed/components/EmbeddedContent/styles.js
- src/screens/Feed/components/MediaTag/styles.js
- src/screens/Feed/components/Post/component.js
- src/screens/Feed/components/Post/styles.js
- src/screens/Feed/components/PostMeta/component.js
- src/screens/Feed/pages/PostCreation/CreatePost.js
- src/screens/Feed/pages/PostDetails.js
- src/screens/Profiles/ProfilePages/index.js
- src/screens/Profiles/ProfilePages/pages/Feed/component.js
- src/screens/Profiles/ProfilePages/pages/Feed/index.js
- src/screens/Profiles/ProfilePages/pages/Summary.js
- src/utils/preprocessFeed.js
- yarn.lock
**Changes:**
- Added hyperlinking.
- Added loading indicator when posting comments.
- Added user feeds and posting to said feeds.
- Removed old embed system and replaced it with new one.
- Android will now use `WebView` instead of the `YouTube` component.
- Youtube video embeds now have auto height adjustments.
- Minor UI fixes.
> Feed embeds

- src/config/api.js
- src/screens/Profiles/MediaPages/index.js
- src/screens/Profiles/MediaPages/pages/Episodes/component.js
- src/screens/Profiles/MediaPages/pages/Reactions/component.js
- src/screens/Profiles/components/SceneHeader/component.js
- Implement the functionality of the 'Add to Library' button
- Implement favoriting of media
- Handle switching between Anime/Manga terminology on the media page
> Media Page Updates

- src/components/StyledText/component.js
- src/screens/Feed/components/Comment/component.js
- src/screens/Feed/components/Comment/styles.js
- src/screens/Feed/components/EmbeddedContent/component.js
- src/screens/Feed/components/GiphyModal/component.js
- src/screens/Feed/components/Post/component.js
- src/screens/Feed/components/Post/styles.js
- src/screens/Feed/components/PostImage/component.js
- src/screens/Feed/pages/PostDetails.js
- src/utils/preprocessFeed.js
**Changes:**
- Added embeds in comments.
- Minor bug/layout fixes.
> Comment embeds

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/kitsu_mobile/MainActivity.java
- android/app/src/main/java/com/kitsu_mobile/MainApplication.java
- android/fastlane/Appfile
- ios/fastlane/Appfile
- ios/fastlane/Deliverfile
- ios/fastlane/Fastfile
- ios/fastlane/Matchfile
- ios/kitsu_mobile.xcodeproj/project.pbxproj
- ios/kitsu_mobile/Base.lproj/LaunchScreen.xib
- ios/kitsu_mobile/Images.xcassets/AppIcon.appiconset/Contents.json
- ios/kitsu_mobile/Info.plist
This changes the bundle id/application id to match that of Aozora on iOS and Android.
> [WIP] Bundle id changes

- src/components/StyledText/component.js
- src/screens/Feed/components/Comment/component.js
- src/screens/Feed/components/Post/component.js
- src/screens/Feed/index.js
- src/screens/Profiles/UserLibrary/components/UserLibraryEditScreen/component.js
**Josh this is not iOS build fixes, please don't merge instantly ;(**
- Fixes crash on library edit when notes were empty
- Fixes onEndReached being called in feed after 1 post is loaded.
- Hides embedded content in comments on NSFW posts that don't have their overlays removed.
> Small bug fixes

- src/components/MediaUploader/MediaSelectionGrid.js
- src/components/MediaUploader/Thumbnail.js
- src/components/Modal/component.js
- src/components/ProfileHeader/component.js
- src/screens/Profiles/ProfilePages/index.js
- src/screens/Profiles/ProfilePages/pages/About/component.js
- src/screens/Profiles/ProfilePages/pages/Groups/component.js
- src/screens/Profiles/ProfilePages/pages/Library/component.js
- src/screens/Profiles/ProfilePages/pages/Summary.js
- src/screens/Profiles/UserLibrary/components/UserLibraryListScreen/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryScreen/component.js
- src/screens/Profiles/components/EditModal/component.js
- src/screens/Profiles/components/EditModal/index.js
- src/screens/Profiles/components/EditModal/styles.js
- src/screens/Profiles/components/SceneHeader/component.js
> Follow/Edit Profile

- src/config/api.js
- src/screens/Feed/components/Post/PostOverlays/NSFWandSpoiler/component.js
- src/screens/Feed/components/Post/PostOverlays/NSFWandSpoiler/index.js
- src/screens/Feed/components/Post/PostOverlays/OverlayBase/styles.js
- src/screens/Feed/components/Post/component.js
- src/screens/Feed/components/Post/styles.js
- src/screens/Feed/index.js
- src/screens/Feed/pages/PostCreation/CreatePost.js
- src/screens/Feed/pages/PostCreation/MediaItem.js
- src/screens/Profiles/ProfilePages/pages/Feed/component.js
- src/screens/Sidebar/SidebarScreen.js
**Changes:**
- Added NSFW and Spoiler tagging.
- Added post overlay for NSFW **and** Spoiler.
- Hide comments of posts tagged with NSFW or Spoiler.
- Show media tags and post status even when overlay is being displayed.
- This ensures that users still know the context of the post.
- Minor crash fixes when `currentUser` is nil.
- This used to stop users from logging out.
> Added NSFW and Spoiler tagging to posts.

- src/screens/Profiles/components/AvatarHeader/component.js
- src/screens/Profiles/components/ReactionBox/component.js
- Fix issue with boolean values being passed to `numberOfLines`
> Fix crash on media reactions

- android/app/src/main/AndroidManifest.xml
- src/App.js
- src/common/utils/url.js
- src/screens/Feed/components/Comment/component.js
- src/screens/Feed/components/Post/components/PostMain/component.js
**Changes:**
- Removed deep linking
- Added custom URL handler for hyperlinks
- This will ignore kitsu `anime`, `manga` and `user` urls
> Disabled deep linking

- src/screens/QuickUpdateScreen/QuickUpdateCard/component.js
- Handle display issue when no `unit` or `nextUnit` exists
- Handle display issue when `unitCount` is not set
> Fix display issues with QuickUpdate

- src/screens/Profiles/MediaPages/pages/Episodes/component.js
- src/screens/Profiles/MediaPages/pages/Franchise/component.js
- src/screens/Profiles/components/MediaRow/component.js
> Media Franchise page

- src/screens/Notifications/NotificationsScreen.js
- src/screens/Profiles/MediaPages/index.js
- src/screens/Profiles/components/AvatarHeader/component.js
- src/screens/Profiles/components/ReactionBox/component.js
- src/screens/Profiles/components/SceneHeader/component.js
- This hopefully fixes notification crashes
- Reaction boxes now show the title in max of 2 lines in the summary page
- Added subtype display in media pages
> [Fix] Notification crash

- src/common/utils/url.js
- src/screens/Feed/components/Comment/component.js
- src/screens/Feed/components/EmbeddedContent/component.js
- src/screens/Feed/components/EmbeddedContent/styles.js
- src/screens/Feed/components/Post/components/PostMain/component.js
- Added `Anime`, `Manga` and `User` embeds.
> Kitsu embeds

- src/screens/Feed/components/CommentTextInput/component.js
- src/screens/Feed/components/CommentTextInput/styles.js
- src/screens/Feed/components/Post/component.js
- src/screens/Feed/pages/PostCreation/CreatePost.js
- src/screens/Feed/pages/PostDetails.js
Also testing a fix for comment box not hugging keyboard on android.
> Added multi-line comments to PostDetails

- src/screens/Profiles/MediaPages/index.js
- src/screens/Profiles/ProfilePages/pages/About/component.js
- src/screens/Profiles/ProfilePages/pages/Reactions/component.js
- src/screens/Profiles/ProfilePages/pages/Summary.js
- src/screens/Profiles/components/EditModal/component.js
- src/screens/Profiles/components/ImageCard/component.js
- src/screens/Profiles/components/PhotoGrid/component.js
- src/screens/QuickUpdateScreen/QuickUpdate.js
- src/screens/QuickUpdateScreen/QuickUpdateEditor/styles.js
- src/screens/Search/SearchResults.js
- src/screens/Search/SearchScreen/index.js
- `SearchResults` will not show placeholders if results are empty
- Disable `SearchResult` navigation if media is `null`
- Fixed crash when viewing characters on media pages
- Fixed crash if reactions don't have an associated media
- Fixed keyboard hiding Bio when editing profile
- Fixed birthday showing up as invalid in about.
- Fixed posting in QU if text is empty
- Added overlay to QU discussion creation.
- Changed to search keyboard in search.
> [Fix] Various bug fixes

- src/screens/QuickUpdateScreen/QuickUpdateCard/component.js
> Don't render progress bar on Quick Update if unitCount is null

- src/components/Counter/component.js
- src/components/Rating/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryEditScreen/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryListCard/component.js
> Library UI Fixes

- .gitignore
- README.md
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/everfox/animetrackerandroid/MainApplication.java
- android/build.gradle
- android/settings.gradle
- ios/Podfile
- ios/Podfile.lock
- ios/fastlane/Fastfile
- ios/kitsu_mobile.xcodeproj/project.pbxproj
- ios/kitsu_mobile.xcworkspace/contents.xcworkspacedata
- package.json
- src/components/Input/component.js
- src/screens/Profiles/ProfilePages/index.js
- src/screens/Profiles/components/EditModal/component.js
- src/screens/Profiles/components/EditModal/styles.js
- yarn.lock
- Replaced old media selection grid with new image picker.
Issues:
- Once avatar/cover is updated, it isn't reflected across the app.
> [Feature] Image picker

- src/screens/Auth/SplashScreen.js
- src/screens/Feed/components/PostMeta/component.js
- src/screens/Feed/components/PostMeta/styles.js
- src/screens/Feed/feedStreams.js
- src/screens/Feed/pages/PostCreation/CreatePost.js
- src/screens/Feed/pages/PostDetails.js
- src/screens/QuickUpdateScreen/QuickUpdate.js
- src/screens/QuickUpdateScreen/QuickUpdateCard/component.js
- src/screens/QuickUpdateScreen/QuickUpdateEditor/component.js
- src/screens/QuickUpdateScreen/QuickUpdateEditor/styles.js
- Disabled anime and manga feeds
- Added GIF support to QU
- Updated QU text for manga
- Fixed infinite loading screen for android
- Fix like count display for comments.
> [Fix] Various fixes + Disabled anime and manga feeds.

- src/store/user/actions.js
- This fixes an issue with commenting and mentions.
> Request slug on current user.

- src/config/api.js
- src/screens/Onboarding/common/RateScreen/screen.js
- src/screens/QuickUpdateScreen/QuickUpdate.js
- src/screens/QuickUpdateScreen/styles.js
- Fixed manga on-boarding
- Added empty state to QU.
> [Fix] On-boarding and QU fixes

- src/common/utils/url.js
- src/components/ProfileHeader/component.js
- src/screens/Profiles/MediaPages/index.js
- src/screens/Profiles/MediaScreen.js
- src/screens/Profiles/ProfilePages/index.js
- src/screens/Profiles/ProfileScreen.js
- src/screens/QuickUpdateScreen/QuickUpdate.js
- src/screens/Sidebar/SidebarScreen.js
- src/screens/Sidebar/common/SidebarHeader.js
- src/utils/coverImage.js
Switched all covers to go through imgix.
> [Feature] Imgix covers

- src/screens/Sidebar/CannyBoard/component.js
- src/screens/Sidebar/common/SidebarHeader.js
- Fixed passing null sso token.
- Switched to try/catch when fetching sso token.
> [Fix] Canny boards

- src/screens/Feed/components/GiphyModal/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryListCard/component.js
- Re-fix up Giphy crash.
- Fix crash if entry doesn't have a status.
> [Fix] Minor crashes

- android/app/build.gradle
- src/config/env.js
**PLEASE MAKE SURE OTHER PRS HAVE BEEN MERGED AND THAT TRAVIS BUILD HAS COMPLETED SUCCESSFULLY**
**AFTER THAT HAS OCCURRED YOU NEED TO DO THE FOLLOWING:**
- Merge PR into `develop`  **AND CANCEL ANDROID BUILD**
- Merge `develop` into `release` **AND CANCEL ANDROID BUILD**
- Merge `release` into `master` **AND CANCEL ANDROID BUILD**
> [READ INSIDE BEFORE MERGE] Set production flag to true.

- src/components/Counter/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryEditScreen/component.js
:arrow_down:
I want to take a look at the library list performance next. I think we might get benefits from a recycle-based list rather than RN's default `FlatList`.
> Update Library Edit Modal

- package-lock.json
- package.json
- src/screens/Profiles/UserLibrary/components/UserLibraryListScreen/component.js
- yarn.lock
- Bring in `recyclerlistview` package
- Update UserLibraryListScreen Component to support new recycle code.
This results in saving a lot of memory and maintaining a good experience in libraries regardless of size.
-----
Can some others test this as well? Make sure there isn't any blank spaces while scrolling.
btw @Mikunj is it possible to do a release build locally?
> [Perf] Switch to RecycleListView on Library

- src/components/StyledText/component.js
- src/components/ViewMoreText/component.js
- src/components/ViewMoreText/index.js
- src/components/ViewMoreText/styles.js
- src/screens/Feed/components/Comment/component.js
- src/screens/Feed/components/Post/components/CommentFlatList/component.js
- src/screens/Feed/components/Post/components/PostMain/component.js
- src/screens/Feed/pages/PostDetails.js
- src/screens/Profiles/components/SceneHeader/component.js
**Note:** An issue i had while testing this was that on some comments it just wouldn't show `View More` or it would have them expanded. I'm not sure if this was an issue with the simulator or iOS because on my android phone it seemed to work properly.
After merging, if the issue persists then i have a fix.
**Changes:**
- Added view more text to feed and comments.
- Replaced old view more in media summary with this new one.
- Fixed feed comment replies ui not updating.
> [Feature] Added view more text

- src/screens/Profiles/UserLibrary/components/UserLibraryEditScreen/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryListCard/component.js
> Library Fixes

- src/routes/quickUpdate.js
- src/screens/QuickUpdateScreen/QuickUpdate.js
- src/screens/QuickUpdateScreen/QuickUpdateCard/component.js
- Fixed crash in QU if no discussions are present.
- Added going to media page when user taps media image or name.
> [Fix] Quick update

- src/constants/app.js
- src/screens/Profiles/components/EditModal/component.js
- src/screens/Profiles/components/EditModal/styles.js
- Reduced cover image dimensions based on android device.
- This should hopefully stop crashes on profile but can't really test myself :(
> [Fix] Android out of memory

- src/App.js
- src/components/NotificationModal/component.js
- src/components/NotificationPopover/component.js
- src/components/NotificationPopover/index.js
- src/components/NotificationPopover/styles.js
- Changed from modal notification to a component notification.
> [Fix] Notification popovers

- src/screens/Intro/IntroScreen.js
- src/screens/Intro/RegistrationScreen.js
- src/screens/Intro/styles.js
- Fixed up app intro screen for smaller devices.
- Fixed smooth scrolling on android.
> [Fix][Layout] Intro screen for smaller devices.

- android/app/src/main/java/com/everfox/animetrackerandroid/MainApplication.java
- This prevented any android devices < 5.0 to crash.
> [Fix] Multidex for android devices.

- ios/kitsu_mobile/Info.plist
- src/components/Card/CardActivity.js
- src/screens/Auth/AuthScreen.js
- src/screens/Feed/components/MediaTag/component.js
- src/screens/Feed/pages/PostCreation/MediaItem.js
- src/screens/Profiles/MediaPages/pages/Episodes/component.js
- src/screens/Profiles/MediaPages/pages/Franchise/component.js
- src/screens/Profiles/MediaPages/pages/Summary.js
- src/screens/Profiles/MediaScreen.js
- src/screens/Profiles/ProfilePages/pages/Groups/component.js
- src/screens/QuickUpdateScreen/QuickUpdateCard/component.js
> [Fix] Crash fixes

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/res/values/styles.xml
- ios/kitsu_mobile.xcodeproj/project.pbxproj
- package.json
- src/screens/Auth/styles.js
- src/screens/Intro/styles.js
- src/screens/Sidebar/CannyBoard/component.js
- src/utils/isX.js
- yarn.lock
- Replaced `WebView` with `WKWebView` for iOS
- Fixed up Intro layout issues with iPhone X
- Fixed some android issues
> [Fix] iOS Canny Bug

- src/components/Forms/SignupForm.js
- src/screens/Auth/AuthScreen.js
- src/store/user/actions.js
This is because of apple review ....
> Removed birthday field from signup.

- src/components/NotificationPopover/component.js
- src/config/middlewares.js
- src/store/auth/actions.js
- Added sentry logging of FB login and Token refreshing.
- Force auth token setting on kitsu requests.
- Minor notification fix.
> Added sentry logging

- ios/kitsu_mobile.xcodeproj/project.pbxproj
> Remove references to unused native packages

- src/screens/Profiles/MediaPages/index.js
- src/screens/Profiles/ProfilePages/index.js
- src/screens/Profiles/components/SceneHeader/component.js
- src/utils/coverImage.js
> Updates for Parallax & cover images

- src/screens/Feed/components/GiphyModal/component.js
- src/utils/fetch-cache.js
Prior to caching we were executing a request to `trending` each time the Giphy component was mounted (1x per comment input).
> Giphy Performance

- src/routes/tabs.js
- src/routes/tabsNotification.js
- src/screens/Feed/components/MediaModal/component.js
- src/screens/Search/SearchScreen/index.js
- src/store/auth/actions.js
- src/store/feed/actions.js
- src/store/user/actions.js
- Fixed up an on boarding issue that may have led to a crash, also added sentry logging to it.
- Fixed up crash in notifications if currentUser id is null.
- Fixed up algolia key is missing crashes
> [Fix] Onboarding and Sentry crashes

- src/screens/Notifications/NotificationsScreen.js
- src/store/feed/actions.js
> Add aired notifications

- src/screens/Search/Lists/UsersList.js
- src/screens/Search/SearchFilter.js
> [Fix] Small Fixes

- src/screens/Profiles/MediaPages/index.js
- src/screens/Profiles/ProfilePages/index.js
This reverts commit 3c6b31ea1f7bde6c7d0cd20392260d3da7400a7d.
> Revert "Set `useNativeDriver` on ParallaxScroll"

- package.json
- src/screens/Feed/components/GiphyModal/component.js
- src/screens/Library/LibraryScreen/component.js
- src/screens/QuickUpdateScreen/QuickUpdate.js
- src/screens/Search/SearchScreen/index.js
- src/screens/Search/SearchScreen/styles.js
:arrow_up: :arrow_down:
Also debounces search so it isn't as jumpy.
> Lazy search tabs

- src/config/api.js
- src/config/middlewares.js
- src/screens/Search/Lists/ResultsList.js
- src/screens/Search/SearchScreen/index.js
- src/utils/getTitleField.js
> Use user title preference

- src/screens/Profiles/components/EditModal/component.js
> Limit about TextInput to 500 ch.

- android/build.gradle
- src/components/Rating/component.js
- src/config/middlewares.js
- src/screens/Auth/SplashScreen.js
- src/screens/Feed/components/PostImage/component.js
- src/screens/Profiles/UserLibrary/components/UserLibraryListCard/component.js
- src/screens/Sidebar/SidebarScreen.js
- src/store/auth/actions.js
- src/store/auth/reducer.js
- src/store/user/actions.js
> [Fix] Bug fixes

- src/screens/Auth/AuthScreen.js
- src/screens/Intro/RegistrationScreen.js
- src/screens/Sidebar/LinkedAccounts.js
- src/store/auth/actions.js
We forgot to do this step and it may be the cause of why some users can't login with facebook to the app.
> [Fix]Properly logout users from facebook sdk.

- src/routes/tabs.js
:arrow_up: ⬇️ 
Drawer will only respond to gestures on top-level routes (Tab routes)
> Disable drawer on sub-routes

- src/screens/Profiles/UserLibrary/components/LibraryEmptyState/component.js
"you've on hold" doesn't make sense to me, so I will leave it as is; unless someone with better grammar skills than me says otherwise.
> you've done it again.

- src/routes/tabs.js
- src/routes/tabsNotification.js
- Match hacky tabsNotification with new code
> Add Drawer routes to top-level list

- src/screens/Feed/components/Post/components/PostHeader/component.js
- src/screens/Feed/components/Post/components/PostHeader/styles.js
> Increase padding on post header actions

- src/screens/Feed/components/Post/component.js
- src/screens/Feed/components/Post/components/PostHeader/component.js
- src/screens/Feed/pages/PostCreation/CreatePost.js
- src/store/user/actions.js
> Post Editing/Deleting

- src/screens/Library/LibraryScreen/component.js
- src/screens/Library/LibraryScreen/tabbar.js
- src/screens/Profiles/components/TabBar/component.js
> Scroll library tabs

- src/screens/Auth/AuthScreen.js
- src/screens/Intro/RegistrationScreen.js
- src/screens/Sidebar/LinkedAccounts.js
> Request email on Facebook login

- src/routes/tabs.js
- src/routes/tabsNotification.js
- src/screens/Library/LibraryScreen/component.js
- src/store/profile/actions.js
> Increase library pagination limit

- src/components/Forms/LoginForm.js
- src/components/Forms/RecoveryForm.js
- src/components/Forms/SignupForm.js
- src/components/PasswordInput/component.js
- src/components/PasswordInput/index.js
- src/components/PasswordInput/styles.js
- src/screens/Auth/AuthScreen.js
- src/screens/Auth/RecoveryScreen.js
- src/screens/Onboarding/Aozora/CreateAccountScreen.js
- src/screens/Profiles/UserLibrary/components/UserLibraryEditScreen/component.js
This PR fixes some minor issues that users experience when signing up or even signing in.
- Improved password matching code
- Added a visibility indicator to password fields
- Improved error display
- Added back navigation to recovery screen.
> [Fix] Signup Issues

- src/components/ImageLightbox/component.js
- src/screens/Feed/components/Comment/component.js
- src/screens/Feed/components/Post/components/PostHeader/component.js
- src/screens/Feed/pages/PostDetails.js
- src/screens/Profiles/MediaPages/index.js
- src/screens/Profiles/MediaPages/pages/Episodes/Unit/component.js
- src/screens/Profiles/MediaPages/pages/Episodes/component.js
- src/screens/Profiles/ProfilePages/index.js
> [Fix] Minor bugs

- src/screens/Feed/components/ImageSortModal/component.js
- src/screens/Feed/components/ImageSortModal/styles.js
- src/screens/Feed/components/PostCreator/PostCreator.js
- src/screens/Feed/components/PostCreator/styles.js
- src/screens/Feed/components/PostImage/component.js
Fixed PostImage size loading on android.
> [Feature] Added max upload size limit.

- .travis.yml
- android/app/build.gradle
- android/app/src/main/java/com/everfox/animetrackerandroid/MainApplication.java
- android/settings.gradle
- ios/Podfile
- ios/kitsu_mobile.xcodeproj/project.pbxproj
- ios/kitsu_mobile/AppDelegate.m
- src/common/utils/url.js
- src/screens/Feed/components/ImageGrid/component.js
- src/screens/Feed/components/PostCreator/PostCreator.js
- src/screens/Feed/components/PostImage/component.js
- src/screens/Feed/components/PostImage/styles.js
- src/utils/imgix.js
- This will show a 'GIF' overlay on all gif images, that originate from Kitsu, in the image grid.
- This only applies to grids which have more than 1 image.
> [Fix] Gifs in Gallery

- android/app/src/main/AndroidManifest.xml
- ios/kitsu_mobile.xcodeproj/project.pbxproj
Need to merge this PR and probably release because google playstore won't allow adding in app purchases.
> Added iAP capabilities to iOS and Android.

- src/components/DatePicker/component.js
- src/components/DatePicker/index.js
- src/components/DatePicker/styles.js
- src/screens/Profiles/MediaPages/index.js
- src/screens/Profiles/MediaPages/pages/Episodes/component.js
- src/screens/Profiles/MediaPages/pages/Episodes/styles.js
- src/screens/Profiles/UserLibrary/components/UserLibraryEditScreen/component.js
- src/store/profile/actions.js
- Added changing dates when editing library entry
- Added indicator to media episode/chapter page to let users know that they can visit the pages in them.
> [Feature] Library Date Editing

- src/config/api.js
- src/screens/Profiles/MediaPages/pages/Episodes/Unit/component.js
Don't load the episode feed on a chapter page!
> [Fix] Feeds for Manga

- src/screens/Profiles/MediaPages/pages/Episodes/Unit/component.js
> Support new `network` property on embed_data.

- android/app/src/main/AndroidManifest.xml
- src/utils/deeplink.js
- Adds deeplinks to feedback
- Testing a fix for deep link not opening on some android devices.
> [Fix] Deeplink fixes

- android/app/src/main/AndroidManifest.xml
- src/screens/Feed/index.js
- Undo launchMode change.
- Register deep links after interactions have run.
> [Fix] Deeplink

- src/screens/Feed/components/Post/components/PostMain/component.js
- src/screens/Feed/components/Post/components/PostStatus/component.js
- src/screens/Feed/pages/PostDetails.js
- src/screens/Profiles/MediaPages/index.js
- src/screens/Profiles/MediaPages/pages/Episodes/Unit/component.js
- src/screens/Profiles/MediaPages/pages/Episodes/Unit/styles.js
- src/screens/Profiles/ProfilePages/index.js
- src/store/feed/actions.js
- src/utils/deeplink.js
- src/utils/notifications.js
This PR fixes previous deep link problems as well as adding support for:
- `anime/<episodes/reactions/franchise>`
- `manga/<chapters/reactions/franchise>`
- `anime/episodes/<number>`
- `manga/chapters/<number>`
- `users/<library/group/reactions>`
> [Fix] Final deep link fixes

- src/screens/Profiles/MediaPages/pages/Summary/component.js
- src/screens/Profiles/MediaPages/pages/Summary/styles.js
- src/screens/Profiles/ProfilePages/pages/Feed/component.js
- Feeds on the Media and Profile pages
> Add "Load More" button to feeds

- src/screens/Profiles/MediaPages/index.js
- src/screens/Profiles/components/Pill/component.js
- src/screens/Profiles/components/SceneHeader/component.js
This PR adds the following:
- View media trailers
- Allows tapping on categories to view other media of that category
> [Feature] Media page features

- ios/fastlane/Fastfile
Doing this because i don't have access to the fastlane match passphrase
> [iOS][Travis] Make travis update certs and provisioning profiles.

- android/app/build.gradle
- android/app/src/main/java/com/everfox/animetrackerandroid/MainActivity.java
- android/app/src/main/java/com/everfox/animetrackerandroid/MainApplication.java
- android/build.gradle
- android/settings.gradle
- ios/Podfile
- ios/Podfile.lock
- ios/kitsu_mobile.xcodeproj/project.pbxproj
- ios/kitsu_mobile/AppDelegate.m
- ios/kitsu_mobile/Info.plist
- package.json
- src/config/api.js
- src/constants/app.js
- src/screens/Feed/index.js
- src/screens/Profiles/MediaPages/pages/Summary/component.js
- src/screens/Profiles/ProfilePages/pages/Feed/component.js
- src/store/user/actions.js
- src/utils/preprocessFeed.js
- src/utils/user.js
- yarn.lock
Depends on #380 so we can take advantage of the utility function to check for Pro status.
> [Feature] Ads
